### ISSUE TITLE
[React] Copy-paste jobs: Fabrik to Porcupine

### ISSUE THREAD

**Issue by TimVanMourik** [TimVanMourik/GiraffeTools#32]
The Giraffe website will be a general tool for creating data analysis repositories on GitHub. An important part of this is the Porcupine workflow editor. This editor is primarily based on [my earlier C++ application](https://timvanmourik.github.io/Porcupine), but a similar editor exists as a web application, [fabrik](http://fabrik.cloudcv.org)*. 

The current porcupine version is largely based on this web application, and I would like to copy some useful implementations into this repo. I copied the relevant part in the app/fabrik and it runs [locally](localhost:8000/fabrik) in DEBUG mode only. This issue is for copying the useful bits from Fabrik and paste them into Porcupine. 

For each of the jobs below, I'm handing out tips/bounties. Please make suggestions to the list if you find new useful projects. Just like I did with issue #1, the bounty on this issue goes the one that contributed most to this issue.
* [ ] Copy from Fabrik jobs. But of course make it prettier if you want 😄 And clearly only copy the useful bits, not blindly large chunks of code.
  * [x] Pretty zoom functionality (#33, @garyaka)
  * [x] the setParams pane, on clicking on a node. (#35, @bakaoh)
  * [x] Hover event on node ('layer' in fabrik terms), provide a tooltip (#34, @maryam21, dependent on #35.
  * [ ] Connect links. (#36, @agni21)
* [ ] Not copy paste, but additions 
  * [x] A list of parameters for each node. (#37, @arun1595)
  * [ ] Load porcupine save file (#38)
  * [x] Make sure that the nav bar is visible above the porcupine React app (#39, @iamonuwa)

I made blank issues for most of them that I'll specify soon, and I'll fund them all with between ~0.04 and 0.1 ETH. If you'd like to claim any particular job already, just leave a comment. 

***Please don't 'start work' on this GitCoin issue, as it won't show up in the explorer anymore***

*Important differences are that Fabrik only allows for single input/output modules, has hard-coded modules, older React/bootstrap/webpack versions, made for a less generic purpose (only deep learning).

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.08 ETH (58.71 USD @ $733.85/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/TimVanMourik/GiraffeTools/32/378).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $8,704.30 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.

 1. [@iamonuwa](https://gitcoin.co/profile/iamonuwa) 

 has committed to working on this project to be completed 4 weeks, 1 day from now.

**Comment by iamonuwa** [comment]
Hello @TimVanMourik am interested in #39 and #36 for now

**Comment by TimVanMourik** [comment]
Cool, let me write those specifications first. I'll @mention you in the description. I have to say though, #36 is  about connection dots that are only created by #37, so that needs to resolved first.

**Comment by maryam21** [comment]
Hi @TimVanMourik , I'd like to work on #34 .

**Comment by garyaka** [comment]
Hi can I work on 33 and what else is not taken yet?

**Comment by TimVanMourik** [comment]
Guys, thank you very much! I did not expect so many people on such short notice, so I'm a bit slow with updating the briefs on all issues. Although that's done now. Please tell me if anything is unclear. Let's see how to work out the interdependencies (mainly on #37, no pressure @arun1595 😉) and thanks @bakaoh for the first initial submission.

**Comment by KennethAshley** [comment]
I can get this across the finish line. what is the status of the work already being done?

**Comment by weberV** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.08 ETH (55.37 USD @ $692.1/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](http://localhost:8000/issue/TimVanMourik/GiraffeTools/32/378).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $10,300.40 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by TimVanMourik** [comment]
Hey guys! It's been three weeks since posting this issue and almost everything has been completed and the last ones look like they're almost done as well! It's still an early stage of the application, but the workflow editor is slowly starting to look like something functional. A great thank you to @iamonuwa, @arun1595, @bakaoh, @garyaka, @maryam21, @agni21 that completed issues and others that helped out here and there (ooh, and @gitcoinbot of course). Especially to @arun1595 for PRs #40, #50, #58, and the continuous communication, so I'd like to offer the bounty on this issue to him 🙂 

There will be a radio silence of ~3 week, as I'll be on vacation for a while and then go to a conference to show off this project, but also the 'gitcoin way' in which it's progressing. After this, I will most likely post another streak of bounties: connecting porcupine to GitHub, adding workflow logic to the app, and implementing the website design (sketches are outsourced to https://fuchsfabrik.agency and WIP).

I truly enjoy this way of #BUIDLing this OSS project and I'm looking forward to working with all of you more!

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 1 day, 11 hours from now. Please review their questions below:


1. [arun1595](https://gitcoin.co/profile/arun1595) has started work. 	
 * Q: No questions at the moment.

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__Work for 0.08 ETH (47.34 USD @ $591.77/ETH) has been submitted by__:

 1. [@arun1595](https://gitcoin.co/profile/arun1595)



@TimVanMourik please take a look at the submitted work:
* (Link Not Provided) by @arun1595

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/TimVanMourik/GiraffeTools/32/378)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
$10,216.67 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__The funding of 0.08 ETH (46.29 USD @ $578.6/ETH) attached to this issue has been approved & issued to @arun1595.__  

 * Learn more at [on the Gitcoin Issue Details page](https://gitcoin.co/issue/TimVanMourik/GiraffeTools/32/378)
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $9,790.78 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by TimVanMourik** [comment]
Closing this issue as most of it is completed, and the remainder is upgraded to new issues of their own. These will appear this week on GitCoin.
